# Generated by Django 4.1.2 on 2022-10-08 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonHasPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.perk')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.person')),
            ],
        ),
    ]
