# Generated by Django 4.1.2 on 2022-10-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_perk_date_added_alter_person_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
