# Generated by Django 4.1.2 on 2022-10-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_person_image_person_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='perks',
            field=models.ManyToManyField(blank=True, to='authenticate.perk'),
        ),
        migrations.DeleteModel(
            name='PersonHasPerk',
        ),
    ]
