# Generated by Django 4.1.2 on 2022-10-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_person_perks_delete_personhasperk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pin',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
