# Generated by Django 4.0.4 on 2022-10-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_person_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pin',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
